### ISSUE TITLE
Update commands in documentation

### ISSUE THREAD

**Issue by rfecher** [locationtech/geowave#1175]
mrToGw is wrong, I think its copied from localToMrGw
http://locationtech.github.io/geowave/commands.html#ingest-mrToGW

Also, I think this is from an 0.9.4-SNAPSHOT build and in general is outdated.  Maybe someone else can help go through all the commands and find deltas.

**Comment by mcarrier7** [comment]
Went through all commands in GeoWave and made commands in sync with 0.9.6 release build. Also added a number of new commands which were not documented previously, and added updates to PR 1178, submitted on 9-11-2017.
