### ISSUE TITLE
Spark SQL

### ISSUE THREAD

**Issue by samchorlton** [locationtech/geowave#1247]
Hi There,

Is anyone able to show me what the syntax would be to provide a lookup of points within a polygon in SparkSQL.

Thanks

Sam

**Comment by blastarr** [comment]
In geowave, you can run a sparksql query by using the 'analytic sql' command. The user-defined spatial function 'geomWithin' would be appropriate for this query.  
  
Well-known-text (WKT) definition for a polygon looks like this:  
> POLYGON ((-94 34, -93 34, -93 35, -94 35, -94 34))  
... in this case, a 1x1 deg box (be sure to close the polygon w/ the first point)  
  
So, putting it all together, if you had a datastore called mystore, you would do this:  

> geowave analytic sql "SELECT * FROM mystore WHERE geomWithin(geom, 'POLYGON ((-94 34, -93 34, -93 35, -94 35, -94 34))')"

**Comment by blastarr** [comment]
Also, check out the [integration test for sparksql](https://github.com/locationtech/geowave/blob/master/test/src/test/java/mil/nga/giat/geowave/test/javaspark/GeoWaveJavaSparkSQLIT.java) for more ideas on how to use it.

**Comment by samchorlton** [comment]
Thanks that was exactly it.
