### ISSUE TITLE
Some config commands fail if config file doesn't exist

### ISSUE THREAD

**Issue by rfecher** [locationtech/geowave#1250]
At least within services `AddHBaseStoreCommand` and `AddSpatialIndexStoreCommand` fail but by listing the config, it'll create the file and from then on all the commands will work.  The workaround for this to be a non-issue is to programmatically run `config list` on service initialization.

**Comment by jamesyarrington** [comment]
I checked a freshly-bootstrapped EMR, and `geowave config addstore` and `geowave config addindex` commands worked.
