### ISSUE TITLE
Ingest from HIVE

### ISSUE THREAD

**Issue by mcammisa75** [locationtech/geowave#1261]
Hi guys, could you suggest me how it is the best way to ingest data that are stored inside an hive table?
Thanks in advance

**Comment by rfecher** [comment]
if the format of the underlying data is one of our existing [supported formats](https://github.com/locationtech/geowave/tree/master/extensions/formats) you can just point geowave ingest routines at that directory on HDFS, or write your own [ingest plugin]((https://github.com/locationtech/geowave/blob/master/core/ingest/src/main/java/mil/nga/giat/geowave/core/ingest/local/LocalFileIngestPlugin.java)) for your particular data.

Alternatively, using HIVE you may be able to use our geotools-vector ingest format (I'm assuming you are probably talking about vector data and not raster, but we also have geotools-raster) and an appropriate JDBC driver.  The geotools-vector format enables ingest of any data source supported by GeoTools which is a very popular project broadly encompassing many underlying data formats.  I have not used geotools-vector to ingest directly from HIVE tables but they do have a [JDBC base datastore](http://docs.geotools.org/latest/userguide/library/jdbc/index.html) and one would just have to extend that to HIVE to be able to use a geotools-vector format to ingest directly into GeoWave.

**Comment by mcammisa75** [comment]
Hi rfecher, thanks for your reply. In Hive I have a table with time and utm coordinates. I suppose that I should make a kind of transformation in order to be ingested. I'm encountering some problems understanding how geowave works and the lack of examples is discouraging me.

**Comment by rfecher** [comment]
@mcammisa75 a transformation that must be done to some extent is to convert the time/UTM coordinates to SimpleFeature objects (its the java type for vector GIS as used in the popular GeoTools library).  Here's [sample code](https://github.com/locationtech/geowave/blob/master/examples/java-api/src/main/java/mil/nga/giat/geowave/examples/ingest/SimpleIngest.java#L57-L80) that builds SimpleFeatures from lat/lon/time tuples.

Once you have the code that can convert your data to SimpleFeatures, you could implement it as a geowave format plugin which would give you access to a variety of ingest techniques, as a geotools datastore as mentioned above which would potentially also open up more opportunities, or the absolute most straightforward way is to simply write the SimpleFeature data directly to GeoWave using GeoWave's programmatic API.  To do so, you must instantiate a GeoWave DataStore which basically just needs the connection info to the desired distributed key-value store.  Here's an example of [creating an Accumulo DataStore](https://github.com/locationtech/geowave/blob/master/examples/java-api/src/main/java/mil/nga/giat/geowave/examples/ingest/SimpleIngestIndexWriter.java#L53-L67), but the mechanics is the same for HBase datastores as well.  Oce you have a datastore you just createIndexWriter and write as in [the example](https://github.com/locationtech/geowave/blob/master/examples/java-api/src/main/java/mil/nga/giat/geowave/examples/ingest/SimpleIngestIndexWriter.java#L106-L122).  Keep in mind, you must close the index writer when finished (this example is using try-with-resources to automate closing the resource).  Does that make sense?

**Comment by mcammisa75** [comment]
Thanks rfercher, I'll try it programmatically. I was just trying to use was it was present inside the product.

Thanks

**Comment by mcammisa75** [comment]
Rfercher, I'm trying to write the code has you mentioned in your reply. I receive an error:

org.apache.hadoop.hbase.client.RetriesExhaustedException: Can't get the locations

while creating the index:

		final IndexWriter indexWriter = geowaveDataStore.createWriter(adapter, index);

do you have any idea?
The dataStore is created by:

public DataStore getDataStore(String zookeepers, String geowaveNamespace) throws IOException {
		BasicHBaseOperations bao = getHBaseOperationsInstance(
				zookeepers,
				geowaveNamespace);
		return getHBaseGeowaveDataStore(bao);
	}
and getHBaseGeowaveDataStore is:

private DataStore getHBaseGeowaveDataStore(
			final BasicHBaseOperations instance) {
		HBaseIndexStore indexStore = new HBaseIndexStore(instance);
		HBaseAdapterStore adapterStore = new HBaseAdapterStore(instance);
		HBaseDataStatisticsStore statisticsStore = new HBaseDataStatisticsStore(instance);
		HBaseAdapterIndexMappingStore indexMappingStore = new HBaseAdapterIndexMappingStore(instance);
		HBaseSecondaryIndexDataStore secondaryIndexDataStore = new HBaseSecondaryIndexDataStore(instance);
		return new HBaseDataStore(indexStore, adapterStore, statisticsStore, indexMappingStore, secondaryIndexDataStore, instance);
	}

I do not receive any error while getting the dataStore.

Thanks in advance
