### ISSUE TITLE
Apache Kudu as Datastore

### ISSUE THREAD

**Issue by choobinejad** [locationtech/geowave#1306]
I've had a great experience using Apache Kudu for time-series spatial data (typically partitioning by time and a geohash). I'm also starting to look at Geowave, and would be interested in using it as a query layer on top of the data I already have in Kudu. 

Any thoughts/discussion on Kudu as a backend for Geowave? I'd be interested in an "official" integration, but also thoughts on a DIY approach.

**Comment by rfecher** [comment]
It appears to me like this is an appropriate suggestion.  In reading about the [design](https://www.cloudera.com/documentation/enterprise/latest/topics/kudu_schema_design.html#primary_keys) in Kudu regarding primary keys and partitioning, it seems to behave at an underlying level like other key-value stores we've worked with. 

We recently put a lot of effort in generalizing our DataStore implementation and in maximizing code re-use across the datastores we've dug deep into so far (Accumulo, HBase, BigTable, Cassandra, and DynamoDB). 

Although the core developers as far as I know don't have bandwidth right now to support in a hands-on capacity an "official" integration, we would be happy to help as a guide. For starters, it seems to me that the closest analog in implementation may be in Cassandra (which is new, so if a relative newcomer does get to looking deep, we'd also appreciate feedback).  We have a "DataStore" interface with a "BaseDataStore" inherited class that is intended to do most of the heavy lifting.  With BaseDataStore the bulk of the implementation goes into DataStoreOperations createReader/Writer/Deleter methods for the primary data storage/retrieval as well as createMetadataReader/Writer/Deleter for the supplemental data used by the system.

Also, generally speaking, in GeoWave the "indexing" approach is pluggable and decoupled from the DataStore implementation (so all proper datastores should get full feature support). We provide spatial and spatio-temporal out of the box with vector and raster data types.

**Comment by choobinejad** [comment]
@rfecher Thanks very much for the response & pointers on where to get started! I plan to work on this as extracurricular time allows... if anyone else is interested in a Kudu datastore, I'd be happy to link up and collaborate.

**Comment by rfecher** [comment]
great news @choobinejad!  We now have fully featured Kudu support thanks to @dannyqiu, @ChesleyTan, @cyzhan1118, @foolhb, and @carolyntang  

Please give it a try and let us know what you think.

**Comment by choobinejad** [comment]
Thanks @rfecher. I'm not working on that particular project any more, but will relay the info for some friends!
