### ISSUE TITLE
yum install from public repo fails

### ISSUE THREAD

**Issue by gcgold** [locationtech/geowave#1322]
Followed the following instruction... (CentOS 7.4)
  rpm -Uvh http://s3.amazonaws.com/geowave-rpms/release/noarch/geowave-repo-1.0-3.noarch.rpm

Then tried 
  yum --enablerepo=geowave search geowave-*

Yum returns errors unable to locate geowave/primary_db
  [Errno 14] Https Error 404

**Comment by rfecher** [comment]
Thanks for letting us know, we'll look into this ASAP and follow up with a resolution.

**Comment by sam-radiant** [comment]
Hi gcgold, 

We pushed a fix to the repo and everything should be working now. You should be able to search the geowave packages with out the wildcard in the search. 

Let us know if have any issues going forward and we will take a look.

Thank you!

**Comment by rfecher** [comment]
thanks @sam-radiant - I tested it and it looks resolved.
