### ISSUE TITLE
Links broken in README.md on: https://github.com/locationtech/geowave

### ISSUE THREAD

**Issue by davewichers** [locationtech/geowave#1341]
In this file, there is this section:

We have Maven artifact repositories (indexes not enabled, but it works in a maven repo fragment)
  Releases: http://geowave-maven.s3-website-us-east-1.amazonaws.com/release
  Snapshots: http://geowave-maven.s3-website-us-east-1.amazonaws.com/snapshot (nightly)

But both the Releases and Snapshots links return responses like:

404 Not Found
  Code: NoSuchKey
  Message: The specified key does not exist.
  Key: release
  RequestId: 9068DBB402F304A7
  HostId: lJrQYayeAtxSbWrdx/Fhp5oaPRpE9VJjvItRm90rJUBvS9Eo5bQKVmn/KDfI7eglAXEtCUAXjqs=

**Comment by rfecher** [comment]
the intended meaning of indexes not being enabled is that it can't be navigated in a browser (because these are simply on S3) but it fully works with maven and the artifacts are available.
