### ISSUE TITLE
Need to upgrade to GeoServer 2.12.4

### ISSUE THREAD

**Issue by davewichers** [locationtech/geowave#1351]
This new release includes upgrades to some libraries that have known vulnerabilities. GeoWave should upgrade to this newest version to benefit from those changes. Their release notes indicate: "This release is made in conjunction with GeoTools 18.4 and GeoWebCache 1.12.4." Not sure if GeoServer uses either of these, but if they do, then they should all be upgraded together.

**Comment by rfecher** [comment]
We released v0.9.8 with updated support for GeoServer 2.13.2 and GeoTools 19.2.
