### ISSUE TITLE
shapefile fields are garbled

### ISSUE THREAD

**Issue by scially** [locationtech/geowave#1386]
when i ingest shapefile, and add layer to geoserver,  some filed(Chinese) in openlayer are garbled, the shapefile charset is GBK,so i try to modify the source code

![_20180904171345](https://user-images.githubusercontent.com/22127608/45022723-838d5d80-b067-11e8-8c31-f79deae79f66.png)

but  invalid. Do you still need to modify other source code?
![_20180904172116 1](https://user-images.githubusercontent.com/22127608/45022749-9142e300-b067-11e8-9bf4-bed691fff639.png)

**Comment by scially** [comment]
![_20180904194347](https://user-images.githubusercontent.com/22127608/45029320-dd4b5300-b07a-11e8-8c1b-4c0ca0780cb6.png)

**Comment by scially** [comment]
Thank you very much, I will try it

**Comment by scially** [comment]
Do you mean that the environment variable GEOWAVE_TOOL_JAVA_OPT will affect both reading dbf and serialization?

**Comment by rfecher** [comment]
short answer "yes"
for clarity, `$GEOWAVE_TOOL_JAVA_OPT` is used within the `geowave` command as a way to insert _any_ options.  `-Dgeowave.charset= ... ` is the option to set a java property that will be picked up and used by both the shapefile/DBF parser and the serialization.

please let us know if this works for you.
