### ISSUE TITLE
how to configure hbase-container-singlejar

### ISSUE THREAD

**Issue by scially** [locationtech/geowave#1391]
when I execute `mvn package -P hbase-container-singlejar`, I can get file: geowave-deploy-0.9.8-SNAPSHOT-hbase.jar,so how should I configure next?

**Comment by rfecher** [comment]
that jar belongs in your `<hbase.dynamic.jars.dir>` directory from the `hbase-site.xml` oif your deployment.  If its on HDFS its probably `/user/hbase/lib` ... our RPM automatically takes care of placing that, but if you are building from source you will have to manually move it to the appropriate location.

alternatively when you crate a datastore configuration via `geowave config addstore ...` you can use the option `--enableServerSideLibrary=false` to disable the use of serverside libraries.  This is going to be worse performance in general so not recommended in production but is simple and easy in development if you want to test something without worrying about the geowave-hbase serverside library.

**Comment by scially** [comment]
thanks...
