### ISSUE TITLE
record  double shapefile meta info using java geotools ingestion and etc problems

### ISSUE THREAD

**Issue by byungwok** [locationtech/geowave#1403]
Nowadays, i'm making a java source based on Geotools to handle Geowave. but i have encountered some problems. So i'd like to get your advice about this troubles.

1. When i ingest shapefile through java-api based on geotools, the both meta data is recorded for one shape file in Accumulo. 
This is the shot i was taken : 

![double record](https://user-images.githubusercontent.com/39606428/45351058-3aea1d00-b5f0-11e8-9d99-4af573b554f1.PNG)

This issue was also in previous jar file version. I try to fix it up on my java client side but i didn't.
This is my java source for ingesting to geowave : 

//-----------------------------------------------------	
public static void main(String[] args) throws Exception {
		
		DataStore dataStore = dataStore(); //connection data for geowave and accumulo
	
		String typeName = "shp file name";
		String filepath = "file path";
		
		writestr(filepath, dataStore);
	}
	
	private static void writedata(String filepath, DataStore dataStore,
			String usrFNm) throws IOException {

		Map<Object, Serializable> shapeParams = new HashMap<Object, Serializable>();

		shapeParams.put("url", new File(filepath).toURI().toURL()); // shp file path
		shapeParams.put("charset", "utf-8");
											

		DataStore shapeDataStore = DataStoreFinder.getDataStore(shapeParams); /

		// feature type
		String typeName = shapeDataStore.getTypeNames()[0]; // taking a file name

		FeatureSource<SimpleFeatureType, SimpleFeature> featSource = shapeDataStore
				.getFeatureSource(typeName);
		FeatureCollection<SimpleFeatureType, SimpleFeature> featSrcCollection = featSource
				.getFeatures(); // gether the feature data

		System.out.println(shapeDataStore);

		SimpleFeatureType ft = shapeDataStore.getSchema(typeName);

		// feature type copy to set the new name
		SimpleFeatureTypeBuilder builder = new SimpleFeatureTypeBuilder();

		builder.setName(typeName); 
		
		builder.setAttributes(ft.getAttributeDescriptors());
		builder.setCRS(ft.getCoordinateReferenceSystem());

		SimpleFeatureType newSchema = builder.buildFeatureType(); 

		Transaction transaction = new DefaultTransaction("create"); 
		
		dataStore.createSchema(newSchema);
		FeatureStore<SimpleFeatureType, SimpleFeature> featStore = (FeatureStore<SimpleFeatureType, SimpleFeature>) dataStore .getFeatureSource(typeName);
		

		featStore.setTransaction(transaction);
		try { 
			featStore.addFeatures(featSrcCollection); 
			transaction.commit(); 

			System.out.println("Incent done");
		} catch (Exception problem) {
			problem.printStackTrace();
			transaction.rollback();
		} finally {

			transaction.close();
		}
	}
	
	
	public static DataStore dataStore() throws Exception {

		DataStore dataStore = null;
		try {
			dataStore = getGeoWaveDataStore();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		if (dataStore == null) {
			return null;
		}
		System.out.println("connection success");
		return dataStore;
	}

	private static DataStore getGeoWaveDataStore() throws IOException {
		return createGeoWaveDataStore();
	}

	public static Map<String, Serializable> getParams() { 
		
		final Map<String, Serializable> params = new HashMap<>();
		params.put("zookeeper", zookeepers);
		params.put("instance", instanceId);
		params.put("user", user);
		params.put("password", password);
		params.put("namespace", tableName);
		params.put("gwNamespace", gwNamespace);

		params.put("Lock Management", "memory");
		params.put("Authorization Management Provider", "empty");
		params.put("Authorization Data URL", null);
		params.put("Transaction Buffer Size", 10000);
		params.put("Query Index Strategy", "Heuristic Match");
		return params;
	}

	private static DataStore createGeoWaveDataStore() throws IOException
	{
		final Map<String, Serializable> params = getParams();
		final boolean useMock = false;
		DataStore dataStore = null;
		try {
			final StoreFactoryFamilySpi storeFactoryFamily;
			if (useMock) {
				storeFactoryFamily = new MemoryStoreFactoryFamily();
			} else {
				storeFactoryFamily = new AccumuloStoreFactoryFamily();
			}
			final GeoWaveGTDataStoreFactory geoWaveGTDataStoreFactory = new GeoWaveGTDataStoreFactory(
					storeFactoryFamily); // geotools 호출
			dataStore = geoWaveGTDataStoreFactory.createDataStore(params); // createNewDataStore(params);
																			
																			
		} catch (IOException e2) {
			;
		}

		return dataStore;
	}
 //-----------------------------------------------------

FYI 'DataStore' is imported form  'org.geotools.data.DataStore'.

2. How to get layer's 'InternalAdapterId' saved inside Accumulo using Geo-tools or the other way?

3. Did you know how to control the Geowave CLI in Java Eclipse? It looks like not to access Accumulo at Geowave-ingest. Don't u have some manual for control this at Eclipse?

This is the source for deal. but not perfect : 
//-------------	
public static void main(String[] args) throws Exception {
	final String[] args1 = StringUtils.split( 
			"ingest localToGW -datastore sejong -f geotools-vector -b "+Ingesting+" -gwNamespace geowave.geowave -instance accumulo -user geowave -password geowave -zookeeper zookeeper:2181", 
			' '); 

			for(String str:args1){ System.out.printf(str);} 
			System.out.println(" "); 
			GeoWaveMain gwm=new GeoWaveMain(); 
			//GeoWaveMain.run(args1); 
			gwm.main(args1); 

			System.out.println("!!!!!!");

	}
 //--------------------
Please answer my questions ASAP

Thank you for ur reading !! :)

**Comment by rfecher** [comment]
While trying to setup GeoWaveMain with the commandline args _should_  work it seems cumbersome.  Our primary programmatic API is also called a [DataStore](https://github.com/locationtech/geowave/blob/v0.9.7/core/store/src/main/java/mil/nga/giat/geowave/core/store/DataStore.java).  We have some simplistic examples of ingesting data using the [IndexWriter](https://github.com/locationtech/geowave/blob/v0.9.7/examples/java-api/src/main/java/mil/nga/giat/geowave/examples/ingest/SimpleIngestIndexWriter.java#L106-L117).
I'm unsure what exactly you're trying to do with these questions.  Basically our intent is that public API access shouldn't require access to the `InternalAdapterStore`.  Were you running into issues without it? If you really were to require it, you can instantiate an `InternalAdapterStoreImpl` given `AccumuloOperations`.  [Here's](https://github.com/locationtech/geowave/blob/v0.9.7/examples/java-api/src/main/java/mil/nga/giat/geowave/examples/ingest/SimpleIngest.java#L135-L149) a simple example of creating the operations

**Comment by byungwok** [comment]
i appreciate your quick answer. I'm gonna consider how to use ur code in my one. And then it is my bad habit to speak specific explanation unclear especially in tech., even my mother tongue as well. lol 

So I try to talk why ask it to u clearly this place but if something is not enough, plz let me know about it. i have fix it up.
As told u above, i'm handling Geowave java -api for viewing on Web in Non-commercial intent. As  unclearly know the Geowave, basic functions such  a uploading shapefile, viewing lists, deleting layer etc. was made by Geotools. And the code above is the result to upload shapefile from window to geowave-Accumulo. but ya file uploading is good but recording meta info in accumulo is not. So, i ask that fist question, reason why double write on there. and how to fix up. Third question is plan B.

Then, why i need to access 'InternalAdapterId', because a searching key in accumulo is typename(=shaep file layer name as well) on previous jar file version. So i built up my code according to that.  The newest jar version updated is not found the layer and meta info. on my source because of InternalAdapterId. All function which i'd written is fallen. so i asking How to get it.

it's the my story why i asking like that. said again plz if you didn't understand something, feel free asking  me.  and then have some the other advice about my problem as well comment anytime Please. 

Thank you
 

Plus. what is setting up the 'shape file Path' in  the 'IndexWriter'???

**Comment by byungwok** [comment]
plus; could i get the 'IndexWriter' code before applying to create 'InternalAdapterId'??? Please

**Comment by byungwok** [comment]
Hi i got the double record problem finally but, sadly it has 'InternalAdapterId' you've added lately. so can i get a previous version before applying that?? SimpleIngestIndexWriter.java and SimpleIngest.java both

**Comment by rfecher** [comment]
an example for you to get the internal adapter ID in your particular case using accumulo is here:
```
InternalAdapterStore internalAdapterStore = new InternalAdapterStoreImpl(new BasicAccumuloOperations(
				zookeepers,
				accumuloInstance,
				accumuloUser,
				accumuloPass,
				geowaveNamespace));
Short internalAdapterId = internalAdapterStore.getInternalAdapterId(<adapter ID>);
```
the <adapter ID> is the one you had been using previously, and its equal to `new ByteArrayId(<feature type name>)`

**Comment by byungwok** [comment]
Thanks very
