### ISSUE TITLE
Accumulo setting for geowave with java api

### ISSUE THREAD

**Issue by byungwok** [locationtech/geowave#1422]
Hi 
As your advice, i'd resolved that issues very well.  i'd checked the ingesting shp file perfectly and had feature value as well through java api which u comment me. i appreciate that again.

 But this week i got a new issue. when i scan shp meta data in Accumulo through both cmd tool and geotools, it didn't work and disconnected with Accumulo T server. Especially it's usually happened to ingest the data using java api. I am very confused because it's working perfectly last week. Can i ask you why Accumulo T server down like that and how to fix it up? I doubt the accumulo setting for fixing up, not sure what i'd touch it. or is it something geowave single jar version problem? very confused.. 

attempted error shot on accumulo : 
![wat the hell](https://user-images.githubusercontent.com/39606428/45658643-28f60600-bb2b-11e8-8bb7-e077f49d65ef.PNG)
 

P.S. Please which file has a environment variable 'GEOWAVE_TOOL_JAVA_OPT=' in commandline tools for encoding charset? is it only setting before maven package or can fix up in jar file?

**Comment by byungwok** [comment]
Plus it's not re-connected again. it's not work after out of this logs;

 '2018-09-18 02:36:01,814 [trace.DistributedTrace] INFO : SpanReceiver org.apache.accumulo.tracer.ZooTraceClient was loaded successfully.

2018-09-18 02:36:01,828 [impl.ServerClient] WARN : There are no tablet servers: check that zookeeper and accumulo are running.'

**Comment by byungwok** [comment]
additionally, stop-all, start-all again and scan geowave meta-data, it's turning off with an error log like "[rpc.Thrift Util] WARN : Failed to open transport to localhost:9997".

**Comment by byungwok** [comment]
![default](https://user-images.githubusercontent.com/39606428/45673573-fc131480-bb65-11e8-9667-5c0916ace177.PNG)

FYI error log shot in tserver log

**Comment by byungwok** [comment]
In communication between the accumulo t-server and the hadoop data node, 'geowave working' has some a lot of influence?  T server logger said that '[log.DfsLogger] INFO : Slow sync cost: 119 ms, current pipeline: [DatanodeInfoWithStorage[hadoop:9866,DS-4e1bf177-ec04-405c-883d-f3c4b7287fb3,DISK]'. nowa i'm using docker hadoop, then is it Hardware or network problem??

**Comment by rfecher** [comment]
it looks to me like you updated the revision of geowave that you are using to ingest data without updating the revision of geowave on HDFS being used by accumulo?

In particular the revision of geowave you are running on accumulo must be prior to this commit: https://github.com/locationtech/geowave/commit/6a351a4aac8f65e6369891152d6689574130f308

My suggestion would be to update everything to v0.9.8 now that it is released.

**Comment by byungwok** [comment]
well...thank you for your answer first. i'm accepting to switch both new 9.8 jar ver. and old 9.8 jar ver.(which not has adapter id that u know) and then checking the hadoop DN-accumulo setting.  Were your answer right, i'd consider to downgrade geowave jar file ver. to 9.7 released. anyway ta ta i'm gonna test as ur advice.

then what about the postscript concerned with encoding?

**Comment by byungwok** [comment]
Plus. Please Did you tell me How to access v0.9.7 through geowave/deploy/pom.xml? 
I need both maven package jar and Maven Dependencies as well so...

**Comment by byungwok** [comment]
Then don't have way to typecast from Short internalAdapterId to String something? 

public static void DeleteRows(String layername, String tablename, String Path)
			throws AccumuloException, AccumuloSecurityException, TableNotFoundException  {
		String prop=Path;
				/*"conf/accumulo-client.properties";*/
		// "D:/eGovFrameDev-3.5.1-64bit/workspace/Geowave_web/conf/accumulo-client.properties";

		
		Connector connector = Connector.builder().usingProperties(prop).build(); //
	    System.out.println("connection"); //연결은 완료
	    System.out.println("Table name: "+tablename);
	    System.out.println(layername);
	    try (BatchWriter bw = connector.createBatchWriter(tablename)) {
	    	
	    	System.out.println("batch writer : "+bw);
	    	
	        deleteRow(layername, connector, bw, tablename); //레이어 명을 박아줌 //여기에도 테이블명 박아줌?????
	       									//hdfs 삭제도 소스가 필요한지 알아봐야 함
	        System.out.println("delete done");
	       //목록을 보여주던지 아니면 다시 돌아가던지
	        
	     }
	}
	 
	public static void deleteRow(String row, Connector connector, BatchWriter bw, String table) 
			throws MutationsRejectedException, TableNotFoundException {
		
		    Mutation mut = new Mutation(row);
			System.out.println("mutaion : "+mut.toString());
			System.out.println("delete row : "+row.toString());
			System.out.println("connection : "+connector.toString());
		    try (Scanner scanner = connector.createScanner(table, Authorizations.EMPTY)) {
		    	
		    	System.out.println(scanner);
		    	
		      scanner.setRange(Range.exact(row));
		      for (Entry<Key,Value> entry : scanner) {
		        mut.putDelete(entry.getKey().getColumnFamily(), entry.getKey().getColumnQualifier());
		      }
		    }
		    bw.addMutation(mut);
		    bw.flush();
		  }

the String layername(=row) which i wanna remove is not found using the internalAdapterId  in Accumulo-API

**Comment by byungwok** [comment]
![marked](https://user-images.githubusercontent.com/39606428/45851660-0a844a80-bd77-11e8-9ee6-013336bc45a2.PNG)

: i'd like to take this marked in accumulo. is it internalAdapterId right? hook up with shp file layer name for example sejong on this shot
