### ISSUE TITLE
Delete only one row(shp layer) in Accumulo through geowave

### ISSUE THREAD

**Issue by byungwok** [locationtech/geowave#1437]
Thank you for your last response

Well i have a one more question about the Geowave.

I'd like to delete only one row info and data ingested by geowave in Accumulo, using a java-api.

But Accumulo -api was block coz of the last renewal geowave ver 0.9.8.

So, I'd be looking for the other way to remove it, then i found  'AccumuloDeleter.java'.

I just wonder that it's working and how to use. Don't you have some example to deal with this java file?

Or not available, Or is it not available, One of methods included 'delete' in "AccumuloOperations.java" can be worked for removing one row in Accumulo? and Do you have examples related with it?
  
Thank you for reading and look forward to hearing from you. :)

**Comment by rfecher** [comment]
there is a `delete` method on `DataStore` that looks exactly like `query` so however you'd formulate a programmatic query using the java API to retrieve that data is exactly how you can delete that data.  There is some changes coming to the API soon to make it more intuitive to formulate queries and deletes
