### ISSUE TITLE
geowave-deploy-1.0.0-SNAPSHOT-accumulo.jar

### ISSUE THREAD

**Issue by byungwok** [locationtech/geowave#1446]
![cdh](https://user-images.githubusercontent.com/39606428/47007809-00861980-d174-11e8-9bc6-68b34a970140.PNG)

Nowadays i'm trying to set the CDH Accumulo for using geowave.
just input a geowave jar file for accumulo in ext directory. However after that all accumulo module is down with that error log above. it can not read and accept the geowave jar file for accumulo avaliable.
In my guess, This logs looks like to relate with commons-vfs2-2.0.jar that CDH has. but not sure.
Something need a new jar file for CDH Accumulo?
as the geowave manual said, i already konw that geowave can be also working with CDH.
So i'd like to seek advice for solving this problem.
I'm looking forward to the fastest possible response.

my System info is;
CDH version : Cloudera Express 5.15.1 (#3 built by jenkins on 20180731-0834 git: 6e046fd999fd99e7e12299386ba69b23afa43c60)
Java version : 1.8.0_181
Accumulo version : 1.7.2-cdh5.5.0

Please let me know advice ASAP

Thank you for your reading

**Comment by byungwok** [comment]
Plus after input the geowave jar file, it does not enter into accumulo shell left this log;
![shell](https://user-images.githubusercontent.com/39606428/47011582-44c9e780-d17d-11e8-8249-0342c46591ac.PNG)

then ingesting the shp file, it can make empty '_GEOWAVE_METADATA' table only.

is it something need the other setting using CDH accumulo?

**Comment by byungwok** [comment]
Plus. 
![scan](https://user-images.githubusercontent.com/39606428/47014340-f3bdf180-d184-11e8-9a97-6d505344ca56.PNG)

when scanning the  'GEOWAVE_METADATA' table, it says the logs

**Comment by rfecher** [comment]
presumably this is a jar you built from the source code yourself?  you can try using our hosted jars [here](http://locationtech.github.io/geowave/packages.html) and make sure the permissions are open enough for the accumulo tablet server process to read (which I'm assuming you already checked but figured I'd mention to make sure).  Using lib/ext locally on each tserver should be fairly straightforward, although we always put the jar on HDFS and use accumulo namespaces as described [here](http://locationtech.github.io/geowave/userguide.html#accumulo-config-overview-procedure)

**Comment by byungwok** [comment]
anybody please show me how to set up the geowave in cloudera? Nobody has some examples about it? rpm set up is not work and then unclear to me then making jar file for tools and accumulo with cloudera is no manual something

**Comment by byungwok** [comment]
Thank you for your quick answer rfecher  you r very faster then my work off...lol
yap this jar file built from the source code myself..coz i'm bad at dealing with rpm..anyway i'll try....im very confuse that cloudera is too different.
is it something different between Cloudera and Apache during the installation process? such a location of accumulo jar file(yep i did that it'd be at 'lib/ext' but not sure it's the same with it) or making geowave tools alias in cloudera? or operation System using tools CLI?

then what is the jars mass( this: http://locationtech.github.io/geowave/packages.html) it's avaliable?

Finally did you have some manual or examples about geowave setting in cloudera?
