### ISSUE TITLE
Geoserver plugin error when creating new geowave data store

### ISSUE THREAD

**Issue by byungwok** [locationtech/geowave#1449]
Hi thank you for your last answer. i did set it up clearly with cdh5.

Now i'm asking and also reporting about a strange phenomenon at geowave-geoserver plugin.
Geosever does not make a new Geowave Datastore -ACCUMULO through geoserver web. but in the opposite case, in other words, that it's ok to type in geowave CLI 'geowave gs addlayer [storename] [opsition]'  on the geowave site. Even if i fill in the same connection info already created by geowave CLI, it'd say same error that 'Error obtaining new data store' or sometimes check the jar fill in /lib dir. 
I tried to fix the geowave-geoserver jar file,  tools jar or geoserver, but it's in vain. 
I have no idea what other people also do. so i have a question about it 'have u seen this error before?' and 'how to fix it?'

version info;
geoserver : 2.13.2
geowave tools jar: 1.0.0-cdh5-tools
geowave accumulo jar : 1.0.0-cdh5-accumulo
geowave geoserver jar : deploy-1.0.0-geoserver ('1.0.0-cdh5-geoserver' is not work at geoserver. The 'gs addlayer' command is not accepted with 404 or 500 error.)
cdh5 name node with accumulo and geoserver is different device. but no matter to ping-pong with cdh5 zookeeper like 'ingest' on cli

it's the logs on geoserver create geowave data store;
![default](https://user-images.githubusercontent.com/39606428/47264120-eae56b00-d54a-11e8-90b9-4537b4815d35.PNG)

Please let me know about it what happen at geoserver and geowave

**Comment by byungwok** [comment]
geowave-geoserver jar file also should be matched with the other geowave jar file for cdh5?
very confused why geoserver-cdh5 is not working at this geoserver then geoserver-deploy is not perfect..

**Comment by rfecher** [comment]
that log doesn't really relate to geowave  - if you can find any stack trace with `org.locationtech.geowave` in it perhaps we can help.  Is it a 404 or 500 error when you try to add the layer via CLI?  If its 500 check the geoserver log right after that for what the server error was.

**Comment by byungwok** [comment]
![default](https://user-images.githubusercontent.com/39606428/47325563-6b1ce500-d69f-11e8-9182-187fa0a67ff4.PNG)

yap the geoserver log is not relate to geowave directly but i think that failure to create geowave Data store is also indirectly concerned in the geowave.
then wat about this one when geoserver is starting up after locating geowave jar file at /lib dir, it's not working with 503 error as geowave-geoserver jar. i guess it's also related with my issue. then you can advice me
