### ISSUE TITLE
How to change charset in main function, when insert shp

### ISSUE THREAD

**Issue by jjd0822** [locationtech/geowave#1460]
I am developing a nifi processor that uses geowave to insert shp data into an accumulo. When I insert shp using processor, fields are garbled.
![shptable](https://user-images.githubusercontent.com/44768511/48049681-c04e1000-e1e2-11e8-8474-3102df56bf35.JPG)
I need to create a nar file using "mvn clean install" when I create an nifi processor. Is there any way to specify the GEOWAVE_CHAR_SET of the StringUtils class in the main function?

**Comment by rfecher** [comment]
the best practice would be to run each JVM that needs to access geowave (such as NiFi) with the Java commandline option `-Dgeowave.charset=<my charset>` . In lieu of that you can programmatically set it as early as possible in the JVM startup using `System.setProperty("geowave.charset","<my charset>");` but you just really should make sure it happens first thing or there could be a race condition within GeoWave. This is why its simply best practice to use a commandline arg.

**Comment by scially** [comment]
and jvm of the geoserver also to configured "-Dgeowave.charset=<my charset>"

**Comment by jjd0822** [comment]
re: Thank you!! so just set -Dgeowave.charset=<my charset> before mvn clean install??

**Comment by scially** [comment]
not~ only when you execute "java -cp ...." add -Dgeowave.charset=charset
```
java -Dgeowave.charset=charset   -cp ....
```

**Comment by jjd0822** [comment]
Then I need to create a nar file in a different way (java-cp ....) than mvn clean install. That case, I can use -Dgeowave.charset = charset?

**Comment by scially** [comment]
nope~ after you compile, 
```
java -Dgeowave.charset=charset -cp $GEOWAVE_HOME/deploy/target/geowave-deploy-1.0.0-SNAPSHOT-tools.jar org.locationtech.geowave.core.cli.GeoWaveMain
```

**Comment by scially** [comment]
![image](https://user-images.githubusercontent.com/22127608/48127970-09c05d00-e2c0-11e8-9e3a-09c8959802e6.png)

**Comment by jjd0822** [comment]
OK thanks!! I will try it

**Comment by jjd0822** [comment]
I still have a problem. I set charset with -Dgeowave.charset=charset, but fields are still garbled. Do I set collectly? 
![image](https://user-images.githubusercontent.com/44768511/48183920-b4458800-e373-11e8-8498-ff14c2b36241.png)
Otherwise how I set this code in commandline?
![image](https://user-images.githubusercontent.com/44768511/48183992-f969ba00-e373-11e8-8073-4fdd1a108bc2.png)

**Comment by jjd0822** [comment]
Why? EPSG is coordinate, not charset And How and where to add '-Dgeowave.charset=EPSG:2097' in geoserver? Please let me know :)

then What about in java? just only need to type in 'System.setProperty("geowave.charset","<my charset>");' you said before? that is all for changing Charset?

**Comment by scially** [comment]
sorry, i spell error, `alias geowave="java -Dgeowave.charset=cp949 -cp /usr/local/.....GeoWaveMain"`

**Comment by rfecher** [comment]
I haven't seen any activity on this in several months.  Thanks for the assist @scially. I assume this is resolved now?
