### ISSUE TITLE
Questions about Geowave-Geoserver plugin error

### ISSUE THREAD

**Issue by byungwok** [locationtech/geowave#1462]
Hi all. 
I have questions about geowave-geoserver plugin. it's ok until before maybe 1~2 months ago update 0.9.8 and early 1.0.0. Recently it's not good to work with geoserver. before guess 2 weeks ago, i asked that geoserver didn't make new geowave data store. but at that time geowave command that 'geowave gs addlayer' was working and good to connect with geoserver for publishing a layer. However nowadays it's all not working. it's all the same environment. Is this coz the jar file version both geowave-accumulo or geowave-geoserver is not correct? anyway i'd attach the error log when i was commanded 'geowave gs addlayer'  and version info.

version info;
geoserver : 2.13.2
geowave tools jar: 1.0.0-cdh5-tools
geowave accumulo jar : 1.0.0-cdh5-accumulo
geowave geoserver jar : deploy-1.0.0-geoserver ('1.0.0-cdh5-geoserver' is not work at geoserver. The 'gs addlayer' command is not accepted with 404 or 500 error.)
cdh5 name node with accumulo and geoserver is different device. but no matter to ping-pong with cdh5 zookeeper like 'ingest' on cli

 it's geowave side typed in 'gs addlayer';
![default](https://user-images.githubusercontent.com/39606428/48104530-474cc800-e277-11e8-8893-9248dd0e1768.PNG)

it's geoserver side after sending geowave command;
![2](https://user-images.githubusercontent.com/39606428/48104584-7f540b00-e277-11e8-9b73-566d00caa8dc.PNG)

the results on geoserver browger;
![3](https://user-images.githubusercontent.com/39606428/48104615-aa3e5f00-e277-11e8-97aa-0807e795dbfc.PNG)
![4](https://user-images.githubusercontent.com/39606428/48104618-aca0b900-e277-11e8-943a-d99b69667979.PNG)

I keep try to fix up using many ways but situation is worse. i think it's not normal. Did i mistake something? so Please let me know what is problem and how to fix up please...ASAP

plus. The geowave-geoserver-1.0.0.jar I made in September is fine.

**Comment by rfecher** [comment]
Sorry, I hope I had answered this on another channel and didn't just completely miss this.  This looks to be pretty clearly a result of our update to GeoServer 2.14.0 ... generally speaking we can be backwards compatible with previous geotools/geoserver releases, but the step to 2.14.0 has breaking changes in the JTS package renaming that make backwards compatibility impossible.  I hope you had found that upgrade your version of GeoServer solves this issue!  And very sorry if I did just completely miss this one earlier.
