### ISSUE TITLE
I ask again about shp charset

### ISSUE THREAD

**Issue by jjd0822** [locationtech/geowave#1463]
I created the java code to load the shp file into the accumulo using geowave. I was asked about the phenomenon that field was garbled when loading shp file into accumulo through geowave.  So I put -Dgeowave.charset = charset in the commandline to change the charset setting, and I put shp with commandline, only the garbled form was changed. (??????->¼­¿ïÆ¯º°½Ã) Please tell me what is problem.

**Comment by jjd0822** [comment]
OK then how to I add -Dgeowave.charset=charset in geoserver? Just like in geowave?

**Comment by scially** [comment]
yes, if you ues tomcat, you should edit $TOMCAT_HOME/bin/catalina.sh

![image](https://user-images.githubusercontent.com/22127608/48330895-41951f00-e689-11e8-8c5b-a9b4a5a00d96.png)

**Comment by jjd0822** [comment]
I'm using Geoserver with jetty. Then still set JAVA_OPTS=-Dgeowave.charset=charset?
This is start.ini file
![image](https://user-images.githubusercontent.com/44768511/48331884-13b5d780-e695-11e8-8e1d-cadfd7fcfa9b.png)

**Comment by scially** [comment]
[https://stackoverflow.com/questions/7647795/passing-java-options-to-jetty-sh](https://stackoverflow.com/questions/7647795/passing-java-options-to-jetty-sh)

**Comment by scially** [comment]
for linux, you can edit startup.sh in bin
![image](https://user-images.githubusercontent.com/22127608/50292958-79279000-04ad-11e9-88ad-a4e60081f058.png)
