### ISSUE TITLE
Is this a bug? about "mil.nga.giat.geowave.core.geotime.store.query.SpatialQuery"

### ISSUE THREAD

**Issue by hw4270** [locationtech/geowave#1469]
when I use SpatialQuery in spark,I got an exception:"java.nio.BufferOverflowException",then I find out this:
`
	@Override

	public byte[] toBinary() {

		final byte[] crsBinary = isDefaultCrs(crsCode) ? new byte[0] : StringUtils.stringToBinary(crsCode);
		final byte[] superBinary = super.toBinary();
		final byte[] geometryBinary = new WKBWriter().write(queryGeometry);
		final ByteBuffer buf = ByteBuffer.allocate(superBinary.length + geometryBinary.length + 16); //when crsCode = 'EPSG:4523',crsBinary.length?

		buf.putInt(compareOp.ordinal());
		buf.putInt(nonSpatialCompareOp.ordinal());
		buf.putInt(crsBinary.length);
		buf.putInt(superBinary.length);
		buf.put(crsBinary);
		buf.put(superBinary);
		buf.put(geometryBinary);

		return buf.array();
	}`

**Comment by rfecher** [comment]
ahh, good catch. I know we use SpatialQuery in spark successfully, but we probably just use EPSG:4326.  It looks to me like you do find a bug with other CRS's and we'll fix it.  Thanks!

**Comment by rfecher** [comment]
map rendering can be a bottleneck even with 2 million polys (depending on your average points per poly, your SLD, and your geoserver instance).  GeoWave retrieval should be an order of magnitude faster than the actual map rendering of the retrieved polygons. How big is your cluster?  Using DistributedRender.sld _should_ do the trick.

Often GeoWebCache is used for larger datasets to handle the map requests at low zoom levels, but it unfortunately is limiting in how dynamic the layer can be.

**Comment by hw4270** [comment]
we have ten servers with:
    Intel E5(4 Cores, 2.4GHz)
    24 GB RAM
    2 TB HDD

must I set up a coprocessor in hbase?
does the geoserver parameter coprocessorJar need to be set?

**Comment by hw4270** [comment]
hi @rfecher , When I debugged the rendering source code, I found that the following code seemed to have some problems.  In line 61 of the “mil.nga.giat.geowave.adapter.vector.render.DistributedRenderCallback” file.
This condition "style instanceof ProcessFunction".  Can you confirm it for me?


![image](https://user-images.githubusercontent.com/41326780/50477690-5f83cc80-0a08-11e9-9ca0-cd910fdbad6e.png)

**Comment by rfecher** [comment]
are you using [this](https://github.com/locationtech/geowave/blob/master/examples/data/slds/DistributedRender.sld#L17-L23) in your SLD?

**Comment by hw4270** [comment]
Yes, I'm using this file. I removed this condition, it worked. 
However, the display efficiency did not meet expectations. Can you tell me the data volume and display speed when you use distributed rendering?

**Comment by rfecher** [comment]
There's another issue on distributed rendering that is open
