### ISSUE TITLE
The mismatch between  HBase all version(1.1.*,1.4.*)  and  guava 25.1-jre in geowave 0.9.8

### ISSUE THREAD

**Issue by hsg77** [locationtech/geowave#1476]
The mismatch between  HBase all version(1.1.*,1.4.*)  and  guava 25.1-jre in geowave 0.9.8

import <guava.version>25.1-jre</guava.version>  in geowave0.9.8
import <guava.version>12.0.1</guava.version>     in geowave0.9.7

hbase 1.1.*, hbase1.2.*,hbase1.3.*,hbase1.4.*   all use  guava12.0.1 version
hbase 2.0.*,hbase2.1.*  all user guava 11.0.2 version

Is it better to use guava 12.0.1 in geowave 0.9.8?

**Comment by rfecher** [comment]
geowave uses HBase shaded client to avoid a direct dependency on old versions of guava (and subsequent classpath mismatching with many other libraries such as geoserver). Any downstream application should also use hbase shaded client and avoid a direct dependency on guava 12.01 or 11.02 if they want it to work with these other libraries.

**Comment by hsg77** [comment]
The jar package geowave-hbase-0.9.8-apache.jar downloaded from the official website is directly copied to hbase/lib in HBase 1.4.6 and reported to be unable to start HBase (start-hbase.sh). The startup error message is: java.lang.NoSuchMethodError: com.google.common.hash.HashFunction.hashInt (I) Lcom/google/common/hash/HashCode;

**Comment by hsg77** [comment]
Gewave-hbase-0.9.8-apache.jar is from http://locationtech.github.io/geowave/packages.html
