### ISSUE TITLE
Is it possible to query for objects that were in position X at time X' and also were in position Y at time Y' ?

### ISSUE THREAD

**Issue by yoav-zibin** [locationtech/geowave#1547]
Hi,
I'm looking for a SpatialTemporal DB that can track moving objects and answer queries of the form: find all objects that were in position X at time X' and also were in position Y at time Y'.
Is it possible to write such a query in GeoWave?
I looked at:
https://github.com/locationtech/geowave/blob/master/examples/java-api/src/main/java/org/locationtech/geowave/examples/query/SpatialTemporalQueryExample.java
But I only saw queries of the form find all objects in some area at some time intervals.

**Comment by rfecher** [comment]
I believe what you're looking for is a spatial temporal join.  We have examples of spatial join such as this notebook: https://github.com/locationtech/geowave/blob/master/examples/data/notebooks/jupyter/geowave-spatial-join.ipynb

Whereas that example uses 2 different datasets, perhaps you're thinking of applying the join to the same dataset which should merely just need a slight adjustment to eliminate pairing the same element with itself in the join. 

Algorithmically, it is a generic multi-dimensional join that would be applicable as a spatial temporal join but the API exposes merely a spatial join operation.  If you're interested in contributing a spatial temporal join, I can share the relevant code and some charts describing the algorithm?

**Comment by rfecher** [comment]
I'm sorry, disregard that response. My initial reaction was thinking you were trying to find space-time colocation of different objects which is a more complex problem than what I just realized you asked.  You want to find when the same object was at two different space/times? The most straightforward approach to that is to apply an object ID intersection of two separate spatial temporal queries.

**Comment by yoav-zibin** [comment]
Thanks for the quick reply :)
