### ISSUE TITLE
Questions about release Geowave ver 1.0.0  and Compatibility with CDH 6.X

### ISSUE THREAD

**Issue by byungwok** [locationtech/geowave#1562]
Hi 
I have questions about your Geowave's plan in the future.
Did you have Concrete official release date for Geowave 1.0.0 soon?
and Did you have a plan to support CDH 6.X, the latest version of cloudera hadoop? is it close?
if it is not trouble to you, Please let me know about it. :)
Thanks
regard

**Comment by rfecher** [comment]
We're working through the official Eclipse process for [1.0.0](https://projects.eclipse.org/projects/locationtech.geowave/releases/1.0.0) with a release review and a graduation review. We hope to be on track for a release June 17 with a Release Candidate (1.0.0-RC1) a couple weeks earlier.

We'd like to keep our dependencies fairly consistent through the 1.0.0 release and have talked about significant updates once we release 1.0.0.  CDH 6.X seems like a reasonable short-term goal after 1.0.0 but often significant updates are also driven by funding.

**Comment by byungwok** [comment]
Thanks very
