### ISSUE TITLE
Provide Easier Mechanics for Custom Indexing

### ISSUE THREAD

**Issue by rfecher** [locationtech/geowave#1652]
One may want to be able to just index their data given some custom logic (such as using a set of enumerated values or a string, or really anything that isn't provided by the numeric index strategy as it is now).  While there are ways currently to add this logic, the third-party code is not as straightforward as it could be.  Ideally there is can just be an interface that needs to be implemented (with arbitrary provided logic) to provide `InsertionIds` from entries and to provide `QueryRanges` from a known constraint type, then queries should be able to work on that index that match the known constraint type.

**Comment by jdgarrett** [comment]
Resolved with #1653
