### ISSUE TITLE
Multi-Index Deletion Maintaining IndexMetadata

### ISSUE THREAD

**Issue by rfecher** [locationtech/geowave#1655]
There's an issue with deletion where the IndexMetadataSet delete callback assumes the GeoWaveRows are from that index when they can be coming from a different index.  So line 111 of IndexMetaDataSet can be inaccurately passing an indexmetadata insertion IDs that don't belong to the associated index.  This can result in incorrect updates at line 609 of TieredSFCIndexStrategy of the metadata, to include potentially index out of bounds exception (if the incoming insertion IDs doesn't have a partition ID, even though the tiered index metadata assumes a partition ID because any insertion ID from that index will have the tier ID).  See commented out test code within GeoWaveCustomIndexIT which should expose this issue.

**Comment by jdgarrett** [comment]
Fixed with #1670
