### ISSUE TITLE
[Bug] Time Bounds Handling through GeoWaveFeatureReader

### ISSUE THREAD

**Issue by hokieg3n1us** [locationtech/geowave#1702]
Logic in the [QueryIndexHelper](https://github.com/locationtech/geowave/blob/689387635e0ca129efeb41c727896d315507ad1b/extensions/adapters/vector/src/main/java/org/locationtech/geowave/adapter/vector/util/QueryIndexHelper.java) produces undesired results through GeoServer. If the bounds of the query fall outside the bounds of available data for the feature, based on the TimeRangeStatistics, it removes the temporal constraints from the query, instead of producing no results. This is documented in the TODO of the clipIndexedTemporalConstraints function.

**Comment by rfecher** [comment]
that TODO was mine - I had noticed very suspect logic there while I was working something else
