### ISSUE TITLE
Unconventional type names cause issues in vector query language

### ISSUE THREAD

**Issue by jdgarrett** [locationtech/geowave#1707]
If a user has a type name that begins with a number or has unsupported characters such as `-`, the vector query language parsing can fail.  The original idea was to support these names by allowing a user to wrap the name in `""` or `[]`.  When doing this, the parser works, but the query fails because the brackets or quotes are included in the type name, which doesn't match the real type name.  To address this, the query grammar needs to be updated to exclude those brackets from the parsed token.

**Comment by richard3d** [comment]
By "grammar" do you mean it is the actual grammar (i.e. in the grammar file) we want to change? Or do we simply need to strip the offending characters when returning the typename in `QualifiedTypeName.java`?

**Comment by jdgarrett** [comment]
I think the best solution would be to solve it at the grammar level so that it works for all `IDENTIFIER` nodes.  That way you could also use brackets or quotes for unconventional column names, etc.
