### ISSUE TITLE
Geowave plugin not work in Geoserver 

### ISSUE THREAD

**Issue by infearOnTheWay** [locationtech/geowave#1711]
Hi,

We add the geowave plugin for geoserver as mentioned at https://locationtech.github.io/geowave/userguide.html#installation. But we only found **GeoWaveRasterFormat** on geoserver admin. In another word, the vector support is not success by the geowave plugin.

The we check the log in geoserver, we found the log belows:
_26 Apr 17:35:10 WARN [util.factory] - Can't load a service for category "DataStoreFactorySpi". Cause is "ServiceConfigurationError: org.geotools.data.DataStoreFactorySpi: Provider org.locationtech.geowave.adapter.vector.plugin.GeoWaveGTDataStoreFactory could not be instantiated"._
Does it mean that vector support is not success, and what is the root cause.
Our Geoserver version is 2.15.1,geotools version is 21.1, and geowave code is just cloned recently.

**Comment by rfecher** [comment]
I haven't dug into this one yet, but can offer a suggestion. I'd suggest giving geoserver 2.14.0 a try which is the version of geoserver that this version of geowave is built for.
While often versions of geowave will work with a variety of versions of geoserver, my first guess is there is a version incompatibility in this case.

**Comment by infearOnTheWay** [comment]
> I haven't dug into this one yet, but can offer a suggestion. I'd suggest giving geoserver 2.14.0 a try which is the version of geoserver that this version of geowave is built for.
> While often versions of geowave will work with a variety of versions of geoserver, my first guess is there is a version incompatibility in this case.

Thanks for your reply@rfecher.
I would like to try your suggestion, but I still have a question. Is 2.14.0 the latest version of geoserver that the current geowave can support? It seems that the latest geoserver version has reached 2.17.0.

**Comment by jdgarrett** [comment]
GeoWave currently only supports up to version 2.14.x of GeoServer.

**Comment by infearOnTheWay** [comment]
> GeoWave currently only supports up to version 2.14.x of GeoServer.

Thanks for your reply ! @jdgarrett
