### ISSUE TITLE
geowave failed to compile, problem with maven-compiler-plugin? 

### ISSUE THREAD

**Issue by tsandio** [locationtech/geowave#1843]
Observed error while building-
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project geowave-core-store: Compilation failure
[ERROR] /Users/terry/Documents/ods/geowave/core/store/src/main/java/org/locationtech/geowave/core/store/base/BaseDataStoreUtils.java:[836,42] incompatible types: inferred type does not conform to equality constraint(s)
[ERROR]     inferred: org.locationtech.geowave.core.store.dimension.NumericDimensionField<capture#1 of ?>
[ERROR]     equality constraints(s): org.locationtech.geowave.core.store.dimension.NumericDimensionField

Possible issue with using newer versions?
java -version
java version "16.0.2" 2021-07-20
Java(TM) SE Runtime Environment (build 16.0.2+7-67)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)

mvn --version
Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)
Maven home: /usr/local/Cellar/maven/3.8.2/libexec
Java version: 16.0.2, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-16.0.2.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "11.2", arch: "x86_64", family: "mac"

Had another build error that required changing the version of spotbugs to 4.2.2
Tried changing version of maven-compiler-plugin to 3.8.1 but did not resolve issue.

Thanks for any help

**Comment by rfecher** [comment]
yep, you are right, its an issue with versions.  We require java 8.

**Comment by tsandio** [comment]
Noted. I will try and downgrade java and maven versions. Just like to point out that your documentation says, `Requires JDK v1.8 or greater`  at https://locationtech.github.io/geowave/devguide.html#build-python-bindings

**Comment by tsandio** [comment]
Rich,

I am still unable to compile geowave. I am now using Java 8 that came built
in with the Mac OS.

java -version

java version "1.8.0_151"

Java(TM) SE Runtime Environment (build 1.8.0_151-b12)

Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)


The problem appears to be Maven related.  I have tried

apache-maven-3.2.1 (requires modification to the pom.xml file for https as
opposed to http)

apache-maven-3.3.9

apache-maven-3.5.4

apache-maven-3.6.3

apache-maven-3.8.2


For example:

mvn --version

*Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)*

Maven home: /usr/local/opt/apache-maven-3.8.2

Java version: 1.8.0_151, vendor: Oracle Corporation, runtime:
/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre

Default locale: en_US, platform encoding: UTF-8

OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"


I continue to get this error:

 mvn clean install

[*INFO*] Scanning for projects...

[*INFO*]
*------------------------------------------------------------------------*

[*INFO*] *BUILD FAILURE*

[*INFO*]
*------------------------------------------------------------------------*

[*INFO*] Total time:  0.066 s

[*INFO*] Finished at: 2021-09-09T12:51:28-05:00

[*INFO*]
*------------------------------------------------------------------------*

[*ERROR*] The goal you specified requires a project to execute but there is
no POM in this directory
(/private/var/folders/pw/tnftfy_91px247x7hmbfmy980000gn/T/hsperfdata_terry).
Please verify you invoked Maven from the correct directory. -> *[Help 1]*


I have tried to test the pom.xml:

mvn -B verify --file /Users/terry/Documents/geowave/pom.xml -X

Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)

Maven home: /usr/local/opt/apache-maven-3.8.2

Java version: 1.8.0_151, vendor: Oracle Corporation, runtime:
/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre

Default locale: en_US, platform encoding: UTF-8

OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"

.....

[INFO] Scanning for projects...

[ERROR] [ERROR] Some problems were encountered while processing the POMs:

[FATAL] Non-readable POM /Users/terry/Documents/geowave/pom.xml:
/Users/terry/Documents/geowave/pom.xml (Operation not permitted) @


For some reason Maven does not like the project pom.xml. Please advise


-Terry
