### ISSUE TITLE
specify required build versions

### ISSUE THREAD

**Issue by tsandio** [locationtech/geowave#1844]
Unable to build geowave, does not recognize pom.xml file - Tried java 8 and maven 3.2.1
mvn clean install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.066 s
[INFO] Finished at: 2021-09-01T13:04:07-06:00
[INFO] Final Memory: 6M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/private/var/folders/pw/tnftfy_91px247x7hmbfmy980000gn/T/hsperfdata_terry). Please verify you invoked Maven from the correct directory. -> [Help 1]

java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

mvn --version
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T11:37:52-06:00)
Maven home: /usr/local/opt/apache-maven-3.2.1
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"

pom file is present
ls
CONTRIBUTING.md	NOTICE		analytics	deploy		docs		extensions	pom.xml		services
LICENSE		README.md	core		dev-resources	examples	migration	python		test

**Comment by tsandio** [comment]
I think that the issue is all Maven related. Possibly with using an older version of Maven. 
I had to make changes to the pom.xml file based upon https://stackoverflow.com/questions/59763531/maven-dependencies-are-failing-with-a-501-error

The problem is using http as opposed to https. This prevented downloading dependencies.
<pluginRepositories>
        <pluginRepository>
            <id>central</id>
            <name>Central Repository</name>
            <url>https://repo.maven.apache.org/maven2</url>
            <layout>default</layout>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <releases>
                <updatePolicy>never</updatePolicy>
            </releases>
        </pluginRepository>
    </pluginRepositories>
	<repositories>
		<repository>
            <id>central</id>
            <name>Central Repository</name>
            <url>https://repo.maven.apache.org/maven2</url>
            <layout>default</layout>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
		<repository>

I also had to use the `-f` switch to point specifically to the pom.xml file even though I was calling Maven from its directory.

mvn clean install -f /Users/terry/Documents/geowave pom.xml
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project  (/Users/terry/Documents/geowave/pom.xml) has 1 error
[ERROR]     Non-readable POM /Users/terry/Documents/geowave/pom.xml: /Users/terry/Documents/geowave/pom.xml (Operation not permitted)

I opened up the permissions on the pom.xml file but continue to have the same error. Please advise

**Comment by rfecher** [comment]
I hate to ask a couple obvious questions but just to make sure, because a couple things in here stand out to me:
The earlier comment said:

> The goal you specified requires a project to execute but there is no POM in this directory (/private/var/folders/pw/tnftfy_91px247x7hmbfmy980000gn/T/hsperfdata_terry). Please verify you invoked Maven from the correct directory
Which to me implies the working directory is /private/var/folders/pw/tnftfy_91px247x7hmbfmy980000gn/T/hsperfdata_terry so it'd be expecting a pom in /private/var/folders/pw/tnftfy_91px247x7hmbfmy980000gn/T/hsperfdata_terry/pom.xml

Then in the more recent comment it says: `mvn clean install -f /Users/terry/Documents/geowave pom.xml` seemingly putting a space between geowave and pom.xml where there should be a `/`

I can say I've used many different versions of maven and while there may have been the issue from stackoverflow with maven 3.2.1 incompatibility with maven central when it switched to requiring HTTPS, but anything relatively recent 3.6+ should be fine.

**Comment by tsandio** [comment]
I have been running clean install from the geowave directory

pwd

/Users/terry/Documents/geowave


When I run Maven without specifying the path

mvn clean install

[*ERROR*] The goal you specified requires a project to execute but there is
no POM in this directory
(/private/var/folders/pw/tnftfy_91px247x7hmbfmy980000gn/T/hsperfdata_terry).
Please verify you invoked Maven from the correct directory. -> *[Help 1]*


*When I run Maven with specifying the path*

mvn clean install -f /Users/terry/Documents/geowave/pom.xml

[*ERROR*]     Non-readable POM /Users/terry/Documents/geowave/pom.xml:
/Users/terry/Documents/geowave/pom.xml (Operation not permitted)


ls -al pom.xml

-rw-r--r--  1 terry  staff  48998 Sep  9 12:42 pom.xml


My pom is the same as the Master branch

git diff master:pom.xml -- pom.xml


mvn --version

*Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)*

Maven home: /usr/local/opt/apache-maven-3.8.2

Java version: 1.8.0_151, vendor: Oracle Corporation, runtime:
/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre

Default locale: en_US, platform encoding: UTF-8

OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"


thanks for any help
