### ISSUE TITLE
hbase datastore  Directory is empty

### ISSUE THREAD

**Issue by zhongshuiyuan** [locationtech/geowave#1845]
I used the windows version to install and installed all the options, but the hbase datastore directory is empty. After starting the geoserver, there are no hbase-related options.

**Comment by rfecher** [comment]
HBase on Windows was broken in the SNAPSHOT version between June 1 2021 and September 21 2021.Thanks for bringing it to our attention - we fixed this recently so please try again and confirm that it works now.
