### ISSUE TITLE
Reduction in the size of the key

### ISSUE THREAD

**Issue by rfecher** [locationtech/geowave#185]
We can reduce the size of the key, at least optimize some of the integer fields that we know are unsigned to use less bits.  Additional we could consider a strategy for minimizing the size of the data ID and/or a strategy to take more advantage of Accumulo's relative key encoding.

**Comment by rfecher** [comment]
This file is where the keys are persisted [AccumuloRowId.java] (../tree/master/geowave-accumulo/src/main/java/mil/nga/giat/geowave/accumulo/AccumuloRowId.java).

In general, saving space on the byte size of the key will be very beneficial and is a good place to optimize. [Here] (http://ngageoint.github.io/geowave/documentation.html#architecture-accumulo) is the high-level concept of the key structure. One thing that is critical is to maintain lexicographic sort order of the Insertion ID portion.

**Comment by rfecher** [comment]
It is important to pay attention to the [relative key encoding] (https://accumulo.apache.org/notable_features.html#performance) that Accumulo supports.

**Comment by viggyprabhu** [comment]
Do we have any documentation for what each of IndexID, AdapterID, DataID represents? The rest seem pretty self explanatory.
