### ISSUE TITLE
Add store DynamoDB 

### ISSUE THREAD

**Issue by pflashgary** [locationtech/geowave#1904]
Hi there, I'm running this command and doesn't seem to fail but not sure where the dynamodb store is created? 

```sh
geowave store add gdelt --gwNamespace geowave.gdelt -t dynamodb --endpoint https://us-east-2.console.aws.amazon.com/dynamodbv2/    
```

or 

```sh 
geowave store add gdelt --gwNamespace geowave.gdelt -t dynamodb --region US_EAST_2 
```

I don't seem to find relevant information on how to provide the AWS credentials? some env variables? AWS_PROFILE?

**Comment by rfecher** [comment]
It looks to me like you are adding the store but not adding data or an index.  The "store" on the CLI is basically preconfigured connection information which you can re-use in any subsequent command.  Perhaps think of it as a remote URL within `git` commands which you give a name and can re-use by name subsequently.  It looks to me as if you are following the quickstart guide by using those namespaces so perhaps continue following along to add indices and ingest data.

Providing the credentials is outside of the scope of what GeoWave handles, it uses the AWS SDK credential provider. There are many ways to provide the credentials, detailed here:
https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/credentials.html

**Comment by pflashgary** [comment]
Many thanks for the quick response. I have added the index and started ingesting, and things happening without any errors, maybe silent failure? But I still don't see the table has actually been created on aws. 

So my question is: will the whole process create a DynamoDB table for me with spatial(_temporal) indexing, Or do we have to provide an endpoint for an existing DynamoDB table?

**Comment by rfecher** [comment]
it should automatically create a table - when you add the store thats just config, when you add the index it'll create a metadata table and when you ingest data it will create a table for the index.  If you don't see any tables something must have gone wrong?  Did you try querying through the geowave CLI?  The quickstart guide shows examples of querying the GDELT data after you ingested it.  If no results come back from that, something definitely went wrong, but if you can see results of a query it must have created something.

**Comment by pflashgary** [comment]
Thanks, I'll dig in a bit more, but for now I'll close this issue.
