### ISSUE TITLE
Can you give access to S3 bucket to download v2.0.1.

### ISSUE THREAD

**Issue by gleb-an** [locationtech/geowave#1915]
I opened the [link](https://locationtech.github.io/geowave/installation-guide.html) and then pressed the Linux link.
What I got I attached.
![Screenshot from 2023-09-05 11-15-50](https://github.com/locationtech/geowave/assets/8939518/47e770e9-7648-4e73-a318-0aa863cce538)

**Comment by rfecher** [comment]
Thanks for pointing that out.  This issue is resolved now, but please let us know if you continue to see any issues!
