### ISSUE TITLE
JavaDoc generation fails under Java 1.8

### ISSUE THREAD

**Issue by spohnan** [locationtech/geowave#271]
The default behavior has changed under 1.8 and it now enforces more rules associated with JavaDoc markup. Long term I guess these should all be addressed, short term I'm looking to disable the new behavior so it matches 1.7.

http://blog.joda.org/2014/02/turning-off-doclint-in-jdk-8-javadoc.html

**Comment by chrisbennight** [comment]
Andy's patch patches the issue, but we should probably make a pass through our javadoc to bring it up to spec for 1.8.   I'll leave this ticket open for that.
