### ISSUE TITLE
Switch to SLF4J

### ISSUE THREAD

**Issue by chrisbennight** [locationtech/geowave#282]
Currently using log4j - we can use the log4j SLF4J plugin, but should swap over to SLF4J statements.

**Comment by rwgdrummer** [comment]
My experience is that SLF4J is a cleaner interface.
It is allows GeoWave to play nice but not forcing log4j directly.  Although, it maybe forced indirectly by dependencies.  

The only con I have seen is the transitive dependencies may slip in SLFJ bindings, potentially causing mismatches in a logger version of the same group (e.g. multiple log4j bindings found).  This is the very problem SL4J is trying to eliminate, pushing the binding decision to deployment environment.  However, not all dependencies play nice.  The errors that arise from this situation are fairly obvious, such as method not found or type not found exceptions during run-time binding.
