### ISSUE TITLE
Documentation / Startup clarifications

### ISSUE THREAD

**Issue by chrisbennight** [locationtech/geowave#330]
Running through the rpm based installation/quickstart, and wanted to flag a few things as need more documentation:
- More information on the packages re: which nodes they should be installed in (explicit; it's implicit in the puppet scripts)
- More information about geowave/geoserver/jetty rpm instance
  - Log file location (and should they be under data_dir?) - takes awhile to startup, people wonder what's up.
  - Web interface url - standard geoserver on 8080 paradigm, but should call it out
  - Some tuning info (can link to geoserver stuff if we want, but stuff like WMS configuraiton, etc.)
- We talked about this, but I think a blog post / narrative on starting from blank would be good.  Don't want to make the docs too conversational, but walking through the process highlights where we need more info.
  - Longer process, but getting an example for standalone, psuedo-distributed, and clustered operations would be good.
- Finally, package some examples that mimic the screenshots we have on the page (since all the parts are there).  Might need to use the ability in the ingest framework to only pull in a window (CQL defined) if running on a small standalone cluster.

**Comment by chrisbennight** [comment]
Some of this might already be covered in #300 as well

**Comment by chrisbennight** [comment]
For the examples, a point of confusion is the suggestion ( a good one  ) to use per Accumulo namespace classloaders, but it's not explicitly stated (or not obvious enough) that the geowave namespace passed (as a -i argument, for instance) needs to be of the format  $ACCUMULO_NAMESPACE.$GEOWAVE_NAMESPACE

**Comment by electricFeel** [comment]
+1. I started looking through GeoWave over the weekend and had difficulty understanding how ingest and querying fit into the broader system. A canonical example would go a long way to increasing adoption. Ideally a small console application that walks through ingest and query concepts to get over the initial friction of getting started with the system.

**Comment by rfecher** [comment]
this is related to  #688

**Comment by mawhitby** [comment]
A quickstart guide was added in pull request #888 that has examples of ingest and queries. Further work on the documentation is still underway.

**Comment by mawhitby** [comment]
Major updates to the Documentation have been made and were part of the 0.9.3 release. Not sure if we want to keep this issue open and reference it for future documentation updates, or close it and open a new issue the next time.
