### ISSUE TITLE
Better documentation for building and running from source or distributable jars

### ISSUE THREAD

**Issue by rwgdrummer** [locationtech/geowave#428]
(1) Check lib jar for manifest in geowave-tools-singlejar to invoke Main class. Otherwise,document the class (GeoWaveMain) to use in the java -cp option).
(2) Add example to put 'jar' into HDFS (e.g. hadoop fs -copyFromLocal)

He is also stated that the singlejar does not have the formats.  Probably ok as long as we document an example including them with either the java jar option or the java -cp option (requiring the fully qualified GeoWaveMain).

**Comment by datasedai** [comment]
For this, just put in some documentation that says that you have to add all the jars that you want to the classpath, and then you have to execute mil.nga.giat ... GeoWaveMain

**Comment by datasedai** [comment]
Our documentation is confusing because it all references this "geowave" command that doesn't exist unless you use the RPMs to install.
