### ISSUE TITLE
Remotely invoked MapReduce Jobs need to be able to specify additional JARs on classpath

### ISSUE THREAD

**Issue by ewilson-radblue** [locationtech/geowave#484]
The recommended method to do this is to to put the JARs in HDFS and add them to the Job's classpath.  Most of the work can be done by the invoker, but as the Job objects are being created within the Tool implementations, GeoWave needs an option to add the JARs to the classpath of the Job.

**Comment by ewilson-radblue** [comment]
Merge fixes the problem for the KDEJobRunner, but the issue still exists for the other tools.  If they are to be remotely runnable, they should have a similar capability.

**Comment by datasedai** [comment]
Isn't there a hadoop option to do this?  Like HADOOP_CLASSPATH or something?
