### ISSUE TITLE
Add support for secondary indices.

### ISSUE THREAD

**Issue by jwomeara** [locationtech/geowave#50]
This is a feature that would be nice to have in the future.  The hope is that we will be able to leverage some of the work done for #17

**Comment by dcy2003** [comment]
There have been a series of informal meetings and emails around this topic.  Eric did a great job capturing the output of most of our discussions on the following Wiki page: 
https://github.com/ngageoint/geowave/wiki/Secondary-Indexing
We will try to keep that page up to date.

**Comment by dcy2003** [comment]
So far I have been focusing on the impact of secondary indexing to the ingest process, and I wanted to see if anyone ( @rfecher @chrisbennight @rwgdrummer @jwomeara  ) has any feedback on the direction I'm going before I get too far down a rabbit hole.  Current status --> https://github.com/ngageoint/geowave/commit/740c417e76f59d0a5a64572913c723e7e3b9987e

**Brief summary:** 
* I added a new protected method called addAdditionalCallbacks() to AccumuloDataStore which is called from ingestInternal().  There is no default implementation, but this gives other data stores (VectorDataStore, for example) the ability to hook into the ingest process.
* VectorDataStore uses this to register a SecondaryIndexingIngestCallback, which iterates the attributes of simple features upon ingest, examining the user data to look for attributes marked for secondary indexing
* I defined a very basic SecondaryIndex interface and abstract class with a few stubbed out implementations (Numeric, Temporal, Text)
* There is a hacky integration test (SecondaryIndexingDriver) that simply acts as a test harness to tie it all together as I go.  This class will mature into a much more sophisticated test as we add support for new statistics based on secondary indices, query planning, etc. 

Please let me know if anyone has any suggestions or thinks I am going in the right/wrong direction.
