### ISSUE TITLE
Refactor Deployment of Jetty for GeoWave Web Components

### ISSUE THREAD

**Issue by spohnan** [locationtech/geowave#505]
When I originally packaged the core components I cheated a bit and started with the prepackaged Jetty/GeoServer zip file and then just chopped out some of the non-relevant demo data. Now that we'd like to also host the REST API and possibly the documentation it would be much cleaner if we installed Jetty as an RPM dependency so we wouldn't have to drag GeoServer into any install that needed an app server.

https://github.com/ngageoint/geowave/blob/master/deploy/packaging/rpm/centos/6/SPECS/geowave.spec#L80

**Comment by datasedai** [comment]
Related to #437
