### ISSUE TITLE
GeoServer feature events

### ISSUE THREAD

**Issue by rwgdrummer** [locationtech/geowave#621]
GeoWaveTransactionManagement notifiesGeoServer of chaneg events.
However, GeoWaveFeatureSource states (by default) the plugin does not fire off events.  Thus, the inherited content datastore does the work.  We have a choice,
pull out the event notification from the plugin or implement the following in GeoWaveFeatureSource.
protected boolean canEvent() {
        return true;
    }

An evaluation of completeness should be considered if we plan to fire off our own events,

**Comment by datasedai** [comment]
We need more GeoServer integration tests, or expand them out more.

Right now, we have an eventing architecture, but we're not actually testing it.  We're relying on GeoServer complaining.

This effort really goes to trying to discover all the different tests we need.
