### ISSUE TITLE
Allow Analytic to set a seperate output store configuration using the input store as a default

### ISSUE THREAD

**Issue by rwgdrummer** [locationtech/geowave#749]
Note.  StoreParameters.OUTPUT_STORE is currently unused.  It should be used in GeoWaveOutputFormatConfiguration.  The command line option should capture output.  Furthermore, the analytic job runner should set up the output to be the same as the input by default, if available.  If not available, then an error message should be displayed and the operation aborted

**Comment by datasedai** [comment]
Is this an issue in CLI?  Did something get broken with GEOWAVE-546?
