### ISSUE TITLE
GeoServer datastore and layer creation through Commandline tools

### ISSUE THREAD

**Issue by rfecher** [locationtech/geowave#786]
This is related to #608

**Comment by blastarr** [comment]
Creating a new project: geowave-cli-geoserver

**Comment by blastarr** [comment]
Refactored the gs-cli commands to adhere to existing design, and changed the top level to 'gs' - so you will have commands that look like:  
> geowave gs addws myworkspace  
  
Workspace, datastore, and vector (feature) layer commands are finished. Next up is some style mgmt, and then the raster commands.  
  
Time permitting, I'll refactor the webapp geoserver service client to leverage this work.

**Comment by blastarr** [comment]
Raster primitive commands complete. Working on simplifying 'add layer' process for vector/raster.

**Comment by blastarr** [comment]
Generic addlayer command complete. Users can now use a simple command like this:  
>  geowave gs addlayer mystore  
Under the hood, it retrieves all layers+types from the geowave store, checks/creates the default or provided geoserver workspace, checks/creates the geoserver datastore or coverage store (depending on the layer's type); and then creates the feature layer or coverage (again depending on layer type).  
  
The command has a --addAll switch, so if there are multiple layers in the store, it will create all the geoserver layers. If the --addAll switch is not provided when there are multiple layers, it will respond with a list of layers (adapter IDs) for the user to choose from.

**Comment by blastarr** [comment]
Still want to add --allVector and --allRaster switches to the addlayer command, for the case when a user has ingested a large amount of feature and raster data into a single store, and may want to create geoserver layers for only one type or the other.
