### ISSUE TITLE
Change MiniAccumuloCluster to "Test" scope for Accumulo DataStore

### ISSUE THREAD

**Issue by datasedai** [locationtech/geowave#787]
Do not include this in "compile" scope.  It basically compiles a bunch of extra items that are un-needed for Accumulo Client.

**Comment by rfecher** [comment]
its re-used in both geowave-test and geowave-examples.  I'm happy to consider better solutions, but the issue will be that putting these utilities in "test" scope would limit code re-use.

**Comment by datasedai** [comment]
Even still, including zookeeper server code, accumulo server code, etc, has to be bloating our deployment jar significantly.
