### ISSUE TITLE
Variant of Nearest Neighbors analytic that does not assume points

### ISSUE THREAD

**Issue by dcy2003** [locationtech/geowave#810]
A use case has emerged for the nearest neighbors analytic that extends beyond points to include lines, polygons, etc. within a certain distance of a geometry.

**Comment by rwgdrummer** [comment]
The NN analytic deals in geometries.  Distance is measured as the closest
distance between two geometries (can be along edges).
Recall from my prior email, geometries  appear in multiple partitions
associated with their neighbors.  A large polygon is hashed into multiple
partitions (just like our duplicate key problem).   However, there is a
BoundaryPartioner that only partitions based on the boundary of the
polygon.  Thus, neighbors need to be some distance from the perimeter.  If
that does not work, then you have some options:
(1) Stick with the default behavior, which performs badly for large number
of large polygons
(2) If the polygons are few, then loop through them and use them as query
constraints in a multi-threaded app
(3) Calculate the tier hierarchy from bottom to top (skip last tier) for
each object starting with the tier with at most for duplicates (as is done
in the default strategy).  Thus, a point has a key for each tier.  A line
polygon probably starts at some middle tier.    An object is close to other
objects of the same relative size sharing the key in their lowest assigned
tier.  The object is also close to any larger object in containing tier
above.  Caution: Do not compare an object more than once.

Algorithm is something like:
  -- for each object, calculate all hash keys for tiers starting with the
tier where there are NO duplicates (or at most four, try either way) up to
tier 1.
  -- submit the object for each hash key (map key) labeling that object
with that key as 'lowest tier' or not.
  -- reduce (share same key) compare all objects marked as 'lowest tier' to
all other object sharing same key
     for objects marked as lowest tier
       for objects
          compare
