### ISSUE TITLE
Support Accumulo 1.8.0

### ISSUE THREAD

**Issue by dcy2003** [locationtech/geowave#891]
Accumulo 1.8.0 was released: https://accumulo.apache.org/release_notes/1.8.0.html with many notable bug fixes, improvements, and new features.  Most notably, it looks like they made some major improvements to ingest performance.

**Comment by keith-turner** [comment]
GeowaveInputFormat can be updated to use the [new tablet location APIs][1] added in 1.8.0.  Currently its calling internal Accumulo code thats not in the public API.

[1]: http://accumulo.apache.org/1.8/apidocs/org/apache/accumulo/core/client/admin/TableOperations.html#locate%28java.lang.String,%20java.util.Collection%29

**Comment by rfecher** [comment]
thanks, upgrading to 1.8 is on our near-term roadmap and we'll look into [your branch](https://github.com/keith-turner/geowave/tree/use_locator_api) for the tablet location API changes.

**Comment by keith-turner** [comment]
1.8.0 has one serious issue [ACCUMULO-4483](https://issues.apache.org/jira/browse/ACCUMULO-4483).  Should get a 1.8.1 out in the near term with a fix for that.

**Comment by roadmapper** [comment]
Just checking on what the status on this is (or what the roadmap progress is for supporting Accumulo 1.8.x); 1.8.1 came out about 6 weeks ago. The 0.9.2.1 release does work with Accumulo 1.8.1, but currently I'm running it with the Accumulo 1.7.3 client library as it seems Geowave wouldn't play nice with the table creation API.

**Comment by rfecher** [comment]
we had been waiting on the 1.8.1 release, but now that its out we plan to work this off as we have spare cycles (if we can't fit it in time for our 0.9.4 release planned for next month, we will likely plan to release 0.9.4.1 specifically with it in mind).  Good to know it still works using the 1.7.3 client library.

**Comment by madhokie** [comment]
Any update on when 1.8 is going to be supported?

**Comment by rfecher** [comment]
Se issue #1122 and PR #1148
