### ISSUE TITLE
can geowave support 3d models  ?

### ISSUE THREAD

**Issue by litterbug23** [locationtech/geowave#993]
can geowave support 3d models ?

**Comment by rfecher** [comment]
yes with a little code - it would require at least a format plugin for this new data type (see [extension/formats](https://github.com/ngageoint/geowave/tree/master/extensions/formats) for examples) and possibly an adapter if it doesn't make sense to convert it to a SimpleFeature ... geometries can be 3D so it *can* be a SimpleFeature, but there may be good reason to use a more native "adapter" for this format ... what format is the 3D model and how do you want it indexed/searched?

**Comment by litterbug23** [comment]
Geoserver + W3DS has WFS capability，3d data format base CityGML. City3DB is a github opensource about that . thanks!

**Comment by litterbug23** [comment]
3DCityDB

**Comment by rfecher** [comment]
sorry for the delayed response -  I'm interested in giving it a shot but *in theory* there shouldn't be any necessary changes to geowave to get this to work.  Assuming there is a geotools extension that will parse CityGML into SimpleFeatures, geowave has an ingest format for `geotools-vector` which will use geotools to parse any supported file-based datastore.  That will result in CityGML SimpleFeatures stored in GeoWave exactly as the geotools file-based datastore parses it, and then it seems it can use GeoServer + W3DS for WFS support.  Anyways, I'd like to give it a shot before saying for sure, but it seems like it might just work out of the box.

**Comment by rfecher** [comment]
I was trying to test this but I could not find a recent version of the W3DS community extension for GeoServer.  The latest I could find was for GeoServer 2.5.  I also think I read somewhere that W3DS was superseded by a proposed OGC standard called 3DPS.  @litterbug23, is this community extension still supported, or at least do you know if its available for GeoServer 2.10.x?

On the positive side, I downloaded a sample CityGML file and it seems I successfully ingested it into GeoWave although I haven't done anything with the data to prove that it all works.

**Comment by litterbug23** [comment]
I was trying to test this but I could not find a recent version of the W3DS community extension for GeoServer. The latest I could find was for GeoServer 2.5. I also think I read somewhere that W3DS was superseded by a proposed OGC standard called 3DPS. @litterbug23, is this community extension still supported, or at least do you know if its available for GeoServer 2.10.x?

On the positive side, I downloaded a sample CityGML file and it seems I successfully ingested it into GeoWave although I haven't done anything with the data to prove that it all works.

**Comment by litterbug23** [comment]
thanks for your reply!

**Comment by rfecher** [comment]
seems like last message is that it works
